version: '2'

volumes:
  opt_esp_volume:
    driver: local
  etc_icinga2_pki_volume:
    driver: local
  var_log_icinga2_volume:
    driver: local

services:
  icinga2satellite:
    build: ./
    image: espfe/icinga2satellite:latest
    container_name: icinga2satellite
    restart: always
    ports:
      - 5665:5665
    volumes:
      - opt_esp_volume:/opt/esp
      - etc_icinga2_pki_volume:/etc/icinga2/pki
      - var_log_icinga2_volume:/var/log/icinga2
    environment:
      NODE_NAME: "icinga2.satelite.dom"
      NODE_ZONE: "CLIENT_ZONE_NAME"
      MASTER_HOST: "ICINGA2.MASTER.HOST"
      MASTER_PORT: "5665"
      PKI_TICKET: "asdfqwerdfasdgdrgasdfasdf"